#server:
#  port: ${random.int[9500,9999]}
#spring:
#  application:
#    name: ic-chapter-provider
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/icourse2.0?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
#    username: root
#    password: 123456
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: MyHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#dubbo:
#  scan:
#    base-packages: com.online.icourse.provider.service
#  protocol:
#    name: dubbo
#    port: 25544
#    serialization: kryo
#  registry:
#    address: nacos://182.92.219.19:8848
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"