spring:
  application:
    name: ic-business-student
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.25.116:8848
dubbo:
  scan:
    base-packages: com.online.icourse.business.config.service,com.online.icourse.business.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.25.116:8848
server:
  port: 8108
management:
  endpoints:
    web:
      exposure:
        include: "*"
icourse:
  doc:
    title: 学生业务文档
    desc: 学生业务Api